# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 03:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorEdificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('rutEmpresa', models.CharField(max_length=13)),
                ('razonSocial', models.CharField(max_length=50)),
                ('fono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('porcentajeDominio', models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='CargoComite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeDominio', models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('gastosComunes', models.IntegerField()),
                ('fondoDeReserva', models.IntegerField()),
                ('lecturaAnterior', models.IntegerField()),
                ('lecturaActual', models.IntegerField()),
                ('aguaCalienteM3', models.IntegerField()),
                ('aguaCalienteCosto', models.IntegerField()),
                ('multasEIntereses', models.IntegerField()),
                ('morosidad', models.IntegerField()),
                ('diferenciaAFavor', models.IntegerField()),
                ('cobroTransbank', models.IntegerField()),
                ('totalACobrar', models.IntegerField()),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.CargoComite')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('reglamento', models.CharField(max_length=100)),
                ('administradorEdificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.AdministradorEdificio')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Ciudad')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Conserje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=1)),
                ('fono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Ciudad')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField(blank=True)),
                ('tipo', models.CharField(choices=[(b'P', b'Propietario'), (b'A', b'Arrendatario')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('metrosCuadrados', models.CharField(max_length=100)),
                ('cantidadBanos', models.IntegerField(default=1)),
                ('cantidadPiezas', models.IntegerField(default=1)),
                ('walkInCloset', models.BooleanField(default=True)),
                ('porcentajeDominio', models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidadPisos', models.IntegerField()),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('porcentajeDominio', models.DecimalField(decimal_places=6, max_digits=7, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='GastoCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egreso', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('valor', models.IntegerField()),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Condominio')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'GruposGasto',
            },
        ),
        migrations.CreateModel(
            name='LecturaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lectura', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='MultaCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeMulta', models.IntegerField()),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Condominio')),
            ],
        ),
        migrations.CreateModel(
            name='MultaEInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='PagoYAbono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=1)),
                ('fono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('unidad_medida', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('grupoGasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.GrupoGasto')),
            ],
            options={
                'verbose_name_plural': 'TiposGasto',
            },
        ),
        migrations.CreateModel(
            name='TipoMultaEInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='multacondominio',
            name='tipoMultaEInteres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.TipoMultaEInteres'),
        ),
        migrations.AddField(
            model_name='lecturaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Servicio'),
        ),
        migrations.AddField(
            model_name='gastocondominio',
            name='tipoGasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.TipoGasto'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Edificio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Residente'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='conserjes',
            field=models.ManyToManyField(related_name='condominios', to='registro.Conserje'),
        ),
        migrations.AddField(
            model_name='comite',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Condominio'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Edificio'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento'),
        ),
        migrations.AddField(
            model_name='balancemensual',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Departamento'),
        ),
        migrations.AddField(
            model_name='administradoredificio',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Ciudad'),
        ),
        migrations.AddField(
            model_name='administradoredificio',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Comuna'),
        ),
    ]
