# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 22:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20160426_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('fecha', models.DateTimeField()),
                ('valor', models.IntegerField()),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Condominio')),
                ('grupoGasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.GrupoGasto')),
            ],
        ),
    ]
